### ISSUE TITLE
Long time no news

### ISSUE THREAD

**Issue by 32ns** [i582/i582#1]
.

**Comment by i582** [comment]
I just saw this issue, everything is fine, I’m making my own language with friends :D

**Comment by 32ns** [comment]
> I just saw this issue, everything is fine, I’m making my own language with friends :D

Considering the time cost and the rapid pace of AI development, I personally feel that creating a new programming language is not wise at this stage. If you have the energy, focusing on integrating existing languages with AI seems more meaningful. When AI can automatically generate programs in machine code, no language will be able to compete with it; after all, people are looking for results, not just the process. Although it may still seem rudimentary now, the pace of language development is far behind that of its evolution.

If you've decided to do this thing, the first thing to consider is not so much the language itself but how it can be integrated with AI. After all, only magic can defeat magic.

**Comment by i582** [comment]
ok
